import {
  PlacementBranch,
  PlacementItem,
  PlacementObjectiveId,
  PlacementSkill,
} from '@/placement/types';

export const PLACEMENT_BASE_ITEM_COUNT = 12;
export const PLACEMENT_MAX_TIE_BREAK_ITEMS = 2;
export const PLACEMENT_MAX_ITEM_COUNT = PLACEMENT_BASE_ITEM_COUNT + PLACEMENT_MAX_TIE_BREAK_ITEMS;

export const sharedPlacementItems: PlacementItem[] = [
  {
    id: 'shared-greeting-understand-morning',
    objectiveId: 'greeting',
    skill: 'comprehension',
    kind: 'choice',
    promptZh: '情境：早上進教室，同學向你打招呼。選出最合適的回應。',
    promptEn: 'A classmate says, “Good morning!”',
    choices: ['Good morning!', 'Good afternoon!', 'Good evening!', 'Goodbye!'],
    answer: 'Good morning!',
    hintZh: '注意現在是早上；選擇時間相符的問候。',
    feedbackZh: '早上見面時，可以用 “Good morning!” 回應相同問候。',
  },
  {
    id: 'shared-request-understand-pencil',
    objectiveId: 'request',
    skill: 'comprehension',
    kind: 'choice',
    promptZh: '情境：你沒有鉛筆，想禮貌地向同學借一枝。選出真正提出需求的句子。',
    promptEn: 'You need to borrow a pencil.',
    choices: [
      'Could I borrow a pencil, please?',
      'I borrowed a pencil yesterday.',
      'Your pencil is on the desk.',
      'Do you draw with a pencil?',
    ],
    answer: 'Could I borrow a pencil, please?',
    hintZh: '找出同時包含請求語氣與 please 的句子。',
    feedbackZh: '“Could I …, please?” 能清楚、禮貌地提出需求。',
  },
  {
    id: 'shared-greeting-produce-morning',
    objectiveId: 'greeting',
    skill: 'production',
    kind: 'reorder',
    promptZh: '情境：早上向老師問候並關心對方。依序點選語塊組成一句話。',
    promptEn: 'Greet your teacher and ask how they are.',
    chunks: ['are', 'morning', 'you', ',', '?', 'good', 'how'],
    answer: ['good', 'morning', ',', 'how', 'are', 'you', '?'],
    hintZh: '先用 good morning 問候，再用 how are you 關心對方。',
    feedbackZh: '“Good morning, how are you?” 先問候，再詢問對方近況。',
  },
  {
    id: 'shared-request-produce-water',
    objectiveId: 'request',
    skill: 'production',
    kind: 'reorder',
    promptZh: '情境：你想禮貌地要一些水。依序點選語塊組成請求。',
    promptEn: 'Ask for some water politely.',
    chunks: ['water', 'please', 'could', '?', 'some', 'have', 'i'],
    answer: ['could', 'i', 'have', 'some', 'water', 'please', '?'],
    hintZh: '可以從 “could i have” 開始，please 放在問號前。',
    feedbackZh: '“Could I have …, please?” 是常見的禮貌請求句型。',
  },
];

export const placementBranchItems: Record<PlacementBranch, PlacementItem[]> = {
  'meaning-support': [
    {
      id: 'meaning-greeting-understand-evening',
      objectiveId: 'greeting',
      skill: 'comprehension',
      kind: 'choice',
      promptZh: '情境：傍晚在門口遇到鄰居。選出時間相符的問候。',
      promptEn: 'You meet your neighbor in the evening.',
      choices: ['Good evening!', 'Good morning!', 'See you tomorrow!', 'Thank you!'],
      answer: 'Good evening!',
      hintZh: 'evening 指傍晚或晚上剛見面時。',
      feedbackZh: '傍晚見面可以說 “Good evening!”。',
    },
    {
      id: 'meaning-greeting-understand-leaving',
      objectiveId: 'greeting',
      skill: 'comprehension',
      kind: 'choice',
      promptZh: '情境：今天的課結束了，你明天還會見到同學。選出合適的道別。',
      promptEn: 'Class is over. You will meet again tomorrow.',
      choices: ['See you tomorrow!', 'Nice to meet you!', 'Good afternoon!', 'Welcome back!'],
      answer: 'See you tomorrow!',
      hintZh: '找出提到「明天再見」的句子。',
      feedbackZh: '確定明天會再見時，可以說 “See you tomorrow!”。',
    },
    {
      id: 'meaning-request-understand-napkin',
      objectiveId: 'request',
      skill: 'comprehension',
      kind: 'choice',
      promptZh: '情境：桌上沒有餐巾，你想請服務人員拿一張。選出禮貌請求。',
      promptEn: 'You need a napkin at the table.',
      choices: [
        'Could I have a napkin, please?',
        'This napkin is white.',
        'I used a napkin earlier.',
        'Where did you buy the napkins?',
      ],
      answer: 'Could I have a napkin, please?',
      hintZh: '你現在要的是一張餐巾，不是在描述或詢問餐巾。',
      feedbackZh: '需要物品時，可以用 “Could I have …, please?”。',
    },
    {
      id: 'meaning-request-understand-help',
      objectiveId: 'request',
      skill: 'comprehension',
      kind: 'choice',
      promptZh: '情境：你的行李太重，想禮貌地請人幫忙。選出合適句子。',
      promptEn: 'Your bag is heavy. Ask someone for help.',
      choices: [
        'Could you help me, please?',
        'Your bag looks heavy.',
        'I helped my friend yesterday.',
        'Do you carry this bag every day?',
      ],
      answer: 'Could you help me, please?',
      hintZh: '找出直接請對方幫忙、但語氣有禮貌的句子。',
      feedbackZh: '“Could you help me, please?” 是禮貌請求協助的方式。',
    },
  ],
  'production-support': [
    {
      id: 'production-greeting-produce-meet',
      objectiveId: 'greeting',
      skill: 'production',
      kind: 'reorder',
      promptZh: '情境：第一次見到新同學。依序點選語塊，表達很高興認識對方。',
      promptEn: 'You meet a new classmate.',
      chunks: ['meet', 'nice', '.', 'you', 'to'],
      answer: ['nice', 'to', 'meet', 'you', '.'],
      hintZh: '這句從 “nice to” 開始。',
      feedbackZh: '第一次見面常用 “Nice to meet you.”。',
    },
    {
      id: 'production-greeting-produce-tomorrow',
      objectiveId: 'greeting',
      skill: 'production',
      kind: 'reorder',
      promptZh: '情境：和明天會在學校見面的朋友道別。依序組成一句話。',
      promptEn: 'Say you will meet again at school tomorrow.',
      chunks: ['tomorrow', 'school', 'see', '!', 'you', 'at'],
      answer: ['see', 'you', 'at', 'school', 'tomorrow', '!'],
      hintZh: '先說 see you，再補充地點與時間。',
      feedbackZh: '“See you at school tomorrow!” 表示明天在學校見。',
    },
    {
      id: 'production-request-produce-table',
      objectiveId: 'request',
      skill: 'production',
      kind: 'reorder',
      promptZh: '情境：你和朋友進餐廳，想要兩人座位。依序組成請求。',
      promptEn: 'Ask for a table for two.',
      chunks: ['two', 'table', ',', 'for', 'please', '.', 'a'],
      answer: ['a', 'table', 'for', 'two', ',', 'please', '.'],
      hintZh: '先說物品，再接 “for two”，最後加 please。',
      feedbackZh: '“A table for two, please.” 能清楚表達人數與需求。',
    },
    {
      id: 'production-request-produce-menu',
      objectiveId: 'request',
      skill: 'production',
      kind: 'reorder',
      promptZh: '情境：你想請服務人員給你菜單。依序組成禮貌請求。',
      promptEn: 'Ask for the menu politely.',
      chunks: ['menu', 'could', 'please', '?', 'the', 'have', 'i'],
      answer: ['could', 'i', 'have', 'the', 'menu', 'please', '?'],
      hintZh: '從 “could i have” 開始。',
      feedbackZh: '請求特定物品時，可說 “Could I have the …, please?”。',
    },
  ],
  balanced: [
    {
      id: 'balanced-greeting-understand-how-are-you',
      objectiveId: 'greeting',
      skill: 'comprehension',
      kind: 'choice',
      promptZh: '情境：朋友問候你的近況。選出能直接回應近況的句子。',
      promptEn: 'A friend asks, “How are you?”',
      choices: ['I’m fine, thank you.', 'Nice to meet you.', 'See you tomorrow.', 'Good evening.'],
      answer: 'I’m fine, thank you.',
      hintZh: '問題在問你現在好不好。',
      feedbackZh: '“I’m fine, thank you.” 能直接回應近況。',
    },
    {
      id: 'balanced-request-understand-seat',
      objectiveId: 'request',
      skill: 'comprehension',
      kind: 'choice',
      promptZh: '情境：你不確定空位能不能坐，想先禮貌詢問。選出合適句子。',
      promptEn: 'You want to use an empty seat.',
      choices: [
        'May I sit here?',
        'I sat here yesterday.',
        'This seat is near the door.',
        'Do you like this seat?',
      ],
      answer: 'May I sit here?',
      hintZh: '找出在行動前先詢問許可的句子。',
      feedbackZh: '“May I …?” 可用來禮貌詢問是否被允許。',
    },
    {
      id: 'balanced-greeting-produce-meet',
      objectiveId: 'greeting',
      skill: 'production',
      kind: 'reorder',
      promptZh: '情境：第一次見到新隊友。依序組成一句問候。',
      promptEn: 'You meet a new teammate.',
      chunks: ['you', '.', 'to', 'nice', 'meet'],
      answer: ['nice', 'to', 'meet', 'you', '.'],
      hintZh: '這句從 “nice to” 開始。',
      feedbackZh: '第一次見面時，可以說 “Nice to meet you.”。',
    },
    {
      id: 'balanced-request-produce-help',
      objectiveId: 'request',
      skill: 'production',
      kind: 'reorder',
      promptZh: '情境：你需要對方協助。依序組成禮貌請求。',
      promptEn: 'Ask someone to help you.',
      chunks: ['please', 'help', 'could', '?', 'me', 'you'],
      answer: ['could', 'you', 'help', 'me', 'please', '?'],
      hintZh: '先用 could 詢問對方，再說動作與受詞。',
      feedbackZh: '“Could you help me, please?” 是清楚的禮貌請求。',
    },
  ],
};

export const confirmationPlacementItems: PlacementItem[] = [
  {
    id: 'confirm-greeting-understand-afternoon',
    objectiveId: 'greeting',
    skill: 'comprehension',
    kind: 'choice',
    promptZh: '確認題：午餐後第一次遇到老師。選出時間相符的問候。',
    promptEn: 'You meet your teacher after lunch.',
    choices: ['Good afternoon!', 'Good morning!', 'Good evening!', 'See you tomorrow!'],
    answer: 'Good afternoon!',
    hintZh: '午餐後、傍晚前通常是 afternoon。',
    feedbackZh: '午後第一次見面可以說 “Good afternoon!”。',
  },
  {
    id: 'confirm-request-understand-eraser',
    objectiveId: 'request',
    skill: 'comprehension',
    kind: 'choice',
    promptZh: '確認題：你寫錯字，想禮貌地借橡皮擦。選出合適句子。',
    promptEn: 'You need to borrow an eraser.',
    choices: [
      'Could I borrow your eraser, please?',
      'Your eraser is very small.',
      'I bought an eraser yesterday.',
      'Do you use a blue eraser?',
    ],
    answer: 'Could I borrow your eraser, please?',
    hintZh: '找出現在提出借用需求的句子。',
    feedbackZh: '借用物品時，“Could I borrow …, please?” 清楚又有禮貌。',
  },
  {
    id: 'confirm-greeting-produce-later',
    objectiveId: 'greeting',
    skill: 'production',
    kind: 'reorder',
    promptZh: '確認題：你等一下還會見到朋友。依序組成一句道別。',
    promptEn: 'Say that you will meet your friend again later.',
    chunks: ['later', 'friend', 'see', '.', 'my', ',', 'you'],
    answer: ['see', 'you', 'later', ',', 'my', 'friend', '.'],
    hintZh: '先說 see you later，再補上對朋友的稱呼。',
    feedbackZh: '“See you later, my friend.” 表示朋友稍後再見。',
  },
  {
    id: 'confirm-request-produce-seat',
    objectiveId: 'request',
    skill: 'production',
    kind: 'reorder',
    promptZh: '確認題：你想先詢問能不能坐在這裡。依序組成句子。',
    promptEn: 'Ask permission to sit here.',
    chunks: ['here', 'may', '?', 'sit', 'i'],
    answer: ['may', 'i', 'sit', 'here', '?'],
    hintZh: '詢問許可時，可從 may i 開始。',
    feedbackZh: '“May I sit here?” 是簡短、禮貌的許可詢問。',
  },
];

export const placementTieBreakItems: Record<
  PlacementObjectiveId,
  Record<PlacementSkill, PlacementItem>
> = {
  greeting: {
    comprehension: {
      id: 'tie-greeting-understand-evening',
      objectiveId: 'greeting',
      skill: 'comprehension',
      kind: 'choice',
      promptZh: '補充確認：晚上遇到校門警衛，選出最合適的招呼。',
      promptEn: 'You meet the school guard in the evening.',
      choices: ['Good evening!', 'Good afternoon!', 'See you later!', 'Welcome back!'],
      answer: 'Good evening!',
      hintZh: 'evening 指傍晚或晚上。',
      feedbackZh: '晚上見面可用 “Good evening!” 問候。',
    },
    production: {
      id: 'tie-greeting-produce-afternoon',
      objectiveId: 'greeting',
      skill: 'production',
      kind: 'reorder',
      promptZh: '補充確認：下午向新同學問候並關心對方。',
      promptEn: 'Greet a new classmate and ask how they are.',
      chunks: ['how', 'afternoon', ',', '?', 'are', 'good', 'you'],
      answer: ['good', 'afternoon', ',', 'how', 'are', 'you', '?'],
      hintZh: '先用 good afternoon 問候，再用 how are you 提問。',
      feedbackZh: '“Good afternoon, how are you?” 適合下午見面時使用。',
    },
  },
  request: {
    comprehension: {
      id: 'tie-request-understand-notebook',
      objectiveId: 'request',
      skill: 'comprehension',
      kind: 'choice',
      promptZh: '補充確認：你需要借一本筆記本，選出禮貌且符合目的的句子。',
      promptEn: 'You need to borrow a notebook.',
      choices: [
        'Could I borrow your notebook, please?',
        'Your notebook is on the chair.',
        'I bought this notebook yesterday.',
        'Do you write in a notebook every day?',
      ],
      answer: 'Could I borrow your notebook, please?',
      hintZh: '尋找同時表達借用、物品與禮貌語氣的句子。',
      feedbackZh: '“Could I borrow ... please?” 可用來禮貌借用物品。',
    },
    production: {
      id: 'tie-request-produce-chair',
      objectiveId: 'request',
      skill: 'production',
      kind: 'reorder',
      promptZh: '補充確認：禮貌詢問能否使用這張椅子。',
      promptEn: 'Ask politely to use this chair.',
      chunks: ['chair', 'could', 'please', '?', 'this', 'use', 'i'],
      answer: ['could', 'i', 'use', 'this', 'chair', 'please', '?'],
      hintZh: '先用 could i 開始，再放動作與物品，最後加 please。',
      feedbackZh: '“Could I use this chair, please?” 是在徵求使用許可。',
    },
  },
};

export const allPlacementItems = [
  ...sharedPlacementItems,
  ...Object.values(placementBranchItems).flat(),
  ...confirmationPlacementItems,
  ...Object.values(placementTieBreakItems).flatMap((items) => Object.values(items)),
];

export const placementItemById = (itemId: string) =>
  allPlacementItems.find((item) => item.id === itemId);
